### ISSUE TITLE
Doesn't work with spaces in the path

### ISSUE THREAD

**Issue by pcr-coding** [skandasoft/open-in-browsers#1]
If there are spaces in the path e.g. `c:\Program Files\MyApp\MyFile.html` the browser opens `file:///C:/Program` and another tab with `Files\MyApp\MyFile.html`.

**Comment by skandasoft** [comment]
need to have a double quote on either side..will get to it.thanks for reporting.

**Comment by skandasoft** [comment]
check the latest patch.

**Comment by skandasoft** [comment]
closing. feel free to reopen if still a issue
