### ISSUE TITLE
Cannot connect to localhost issue

### ISSUE THREAD

**Issue by AbryceT** [skandasoft/open-in-browsers#10]
Hello,

I have discovered that I cannot connect to localhost with the open-in-browser. For any browser; chrome IE 11, or Firefox. Have tried clearing caches and resetting browsers but still no luck.

Any ideas, I loved this package.

AbryceT

**Comment by AbryceT** [comment]
BA! Nevermind fixed it. I tried setting the default to 8080 and that still didn't fix it. Later I reset the port back to 3000, restarted and it worked...

No idea why 

By the way, great package!!

AlfredT

**Comment by skandasoft** [comment]
thanks for trying it out. not sure why..closing the issue
