### ISSUE TITLE
Unable to open in any browser from this Atom Packages

### ISSUE THREAD

**Issue by taziobaker** [skandasoft/open-in-browsers#15]
If I right click on the html file from the folder and select open with whichever browser, it opens fine with the address bar pointing to:
file:///C:/Users/[username]/Documents/web/blog/LifezSoundtrack/test.html

but when I right click from Atom on the html file and select Open In Browsers the address bar points:
http://localhost:3000/LifezSoundtrack/test.html
And displays message:
This site can’t be reached
localhost refused to connect.

Please help.
I'm running on Windows 10 and tried on Chrome, Firefox and Edge. From Atom Edge does not even attempts to open.

**Comment by skandasoft** [comment]
I think you might have switched the local host setting. Check in the settings for this package. I am switching off by default with the latest patch. Fixed the Edge. Please check out the latest patch.

**Comment by skandasoft** [comment]
closing...assuming issue fixed..feel free to reopen
