### ISSUE TITLE
Any way to change default browser from Chrome?

### ISSUE THREAD

**Issue by JustGleb** [skandasoft/open-in-browsers#16]
Thanks for a great package, but I struggle to find any way to make files open in ChromePortable (which is really Yandex Browser) by default. 
Now when I start Atom, the first attempt to use the package results in opening Google Chrome, even though it isn't even my default browser, and only after I manually open anything in ChromePortable, next links will open in it as well.
I tried to deselect Chrome in settings, remove it from the list of browsers, and so on, but to no avail.
Is there even a way to fix/change this?

P.S. I use Windows 10, if it matters.

**Comment by skandasoft** [comment]
You can maintain in Settings. You can select from drop down

**Comment by skandasoft** [comment]
closing...assuming issue fixed with latest patch..feel free to reopen
