### ISSUE TITLE
Opens the wrong Chrome

### ISSUE THREAD

**Issue by benjaminjrobin** [skandasoft/open-in-browsers#19]
I'm on a Mac, which also has Parallels to run Windows 10, and this plug-in opens Parallels to run Chrome on the Windows side instead of the Mac version by default.

**Comment by skandasoft** [comment]
I basically call the command to start chrome..based on the OS..I am not sure what might be happening.

**Comment by benjaminjrobin** [comment]
I was able to find a temporary work around by delete the shortcut to the Windows version of Chrome from the Mac side.

**Comment by skandasoft** [comment]
I have no way a testing this..if you have any suggestion feel free to update this thread.
