### ISSUE TITLE
It does not open the page in default browser by open-in-browsers:toggle

### ISSUE THREAD

**Issue by denspit** [skandasoft/open-in-browsers#2]
It does not open the page in default browser by pressing a hotkey or button open-in-browsers>toggle

**Comment by ghost** [comment]
It work with the browser icon at the bottom of Atom.
but how can I use shortcut keys to active it ?
window7 x64
Atom 1.4.1
chrome 48.0.2564.97

**Comment by skandasoft** [comment]
can you check the latest patch

**Comment by ghost** [comment]
It works now. Ecellent!
