### ISSUE TITLE
Open FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by ghost** [skandasoft/open-in-browsers#20]
How can I add this browser in options ?

**Comment by skandasoft** [comment]
can you send the command for this. I can add it.

**Comment by Tony-Thomas** [comment]
Would also love to add FirefoxDeveloperEdition.. I couldn't figure out how to modify code to replace the standard browser. How would I go about doing that?

**Comment by skandasoft** [comment]
send the command you would use for the opening from command prompt. also need the os version

**Comment by skandasoft** [comment]
check the latest version and fill in your browsers path in one of the filler browsers
