### ISSUE TITLE
Open in Edge is not working properly

### ISSUE THREAD

**Issue by malozaibi** [skandasoft/open-in-browsers#22]
Hello, 
I like you package. 
After I enabled edge option in the setting, I tried it and it didn't work as expected.
When I click the icon or right click then open in Edge, it opens Edge but with a white page!
Is not even the default blank page that gives you the ability to search and so on.
No, It looks like this

http://imgur.com/PqpCtZA

I hope to fix this soon :)

**Comment by skandasoft** [comment]
can you try opening the file and from the status bar click on the edge icon..btw what is the command you use for opening file in edge

**Comment by malozaibi** [comment]
It won't open even from the status bar.
I didn't add any command. I just activated the option in the package setting.
I found this code in the package / lib / config.coffee

```
Edge:
          cmd: 'start microsoft-edge:'
```

Notice: I updated to the latest version of the package and the problem still present

**Comment by NFiorentini** [comment]
I'm experiencing the same problem as malozaibi.

**Comment by sednagame** [comment]
same here.

**Comment by skandasoft** [comment]
file protocol not recognized by Microsoft-edge. Once it is supported this package would work from edge
