### ISSUE TITLE
Stick to just localhost when the page can't be loaded

### ISSUE THREAD

**Issue by pingshunhuangalex** [skandasoft/open-in-browsers#27]
Hi @skandasoft 
I just downloaded open-in-browsers. Except for not being able to auto-refresh the browser when changes are made, everything looks like exactly what I need.

However, when I started using it, I found otherwise. Since I'm using Django for my framework, all url to the webpages are customised, i.e. having browser open localhost:8000/././.html is not gonna work for me as the url has already been set to something else.

Just wonder is it possible to just load localhost:8000 (or whatever localhost I put in the settings) when the file fails to load. If this is too tricky, then can I at least have the option to set my default page to be localhost:8000 no matter what files I opened? Otherwise, this package is not useful to me. Thanks.

**Comment by skandasoft** [comment]
check out the [pp](http://GitHub.com/skandasoft/pp) package for more details
