### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by tajnymag** [skandasoft/open-in-browsers#3]
Could you please add support for the new MS Edge? It's getting very popular nowadays.

**Comment by Anandajoti** [comment]
I will second that.

**Comment by skandasoft** [comment]
what is the cmd for it for eg internet explorer it is iexplore (start iexplore).

**Comment by Anandajoti** [comment]
start microsoft-edge: (must include the semi-colon, at least on my system).

**Comment by skandasoft** [comment]
check the latest patch. didn't get a chance to test it(start microsoft-edge )

**Comment by RicardoAbad** [comment]
"start microsoft-edge: (must include the semi-colon, at least on my system)" . --from Anandajoti  --.

The browser opens a empty tab but don't a tab with the file loaded. 
Windows 10 user.

**Comment by skandasoft** [comment]
Can you check the latest patch.  It is the colon right(:)
