### ISSUE TITLE
Google Chrome Canary support

### ISSUE THREAD

**Issue by runar-rkmedia** [skandasoft/open-in-browsers#32]
There is currently no support for Google Chrome Canary. Could this be added?

**Comment by skandasoft** [comment]
You can use the chrome portable placeholder and enter the path to the chrome canary exe in the setting for this package

for eg..

C:\Users\xxxx\AppData\Local\Google\**"**Chrome SxS**"**\Application\chrome.exe(if there are space enclose in double quotes)

**Comment by swiftwind0405** [comment]
@skandasoft Where is the path on Mac?
I have tried this, but id doesn't work.
/Applications/Google Chrome Canary.app/
