### ISSUE TITLE
Cannot find path for Google Chrome Portable

### ISSUE THREAD

**Issue by DestructiveBurn** [skandasoft/open-in-browsers#34]
I'm having issues with your plugin trying to open GoogleChromePortable.exe
I had the folder on the desktop and no luck and added it here:
C:\Program Files (x86)\GoogleChromePortable\GoogleChromePortable.exe

It say's:
Windows cannot find: C:\Program'.Make sure you typed the name correctly, and then try again.

**Comment by EdwinHuijsing** [comment]
In Windows you need to add the quotes you should have 
`"C:\Program Files (x86)\GoogleChromePortable\GoogleChromePortable.exe"`

HTH

**Comment by skandasoft** [comment]
Try C:\"Program Files\Mozilla Firefox"\firefox.exe...use double quote for path with the space.

**Comment by zisheng-ai** [comment]
But I am not still have this trouble.

**Comment by niu66677** [comment]
Atom 软件# **安装插件失败**，需要什么设置吗？大师们求教！

**Comment by idaibin** [comment]
mac os 有parallels Desktop这个软件，每次打开chrome时，都会启动该软件并打开该软件中的chrome，而不是使用本机的chrome
