### ISSUE TITLE
Can't open Chrome out of the box

### ISSUE THREAD

**Issue by EdwinHuijsing** [skandasoft/open-in-browsers#38]
While testing i tried to use Chrome, but no chrome and no message could be found.
Firefox work, so i opened the code to check.
In lib/config.coffee i changed this
``` coffee
      linux:
        Chrome:
-         cmd: 'google-chrome '
+         cmd: 'chromium-browser '
        Firefox:
          cmd: 'firefox '
        Safari:
          cmd: 'safari '
        Opera:
          cmd: 'opera '
```
This is on Megeia, i don't know about other distros.
Can it be that the Chrome command line name is different on other distros?

**Comment by skandasoft** [comment]
can you check in command prompt what will work for chrome and send me the details

**Comment by skandasoft** [comment]
Use your own path in the filler browsers ..in the latest patch
