### ISSUE TITLE
0.0.27 and 0.0.28 kill keybindings

### ISSUE THREAD

**Issue by pdxwolfy** [skandasoft/open-in-browsers#42]
Under Atom 1.17.2 on macOS 10.12.5, both 0.0.27 and 0.0.28 result in a settings page that does not show the Keybindings section. In addition, the keybindings present don't work at all. Reverting back to 0.0.26 restores the keybindings section and their behavior.

**Comment by skandasoft** [comment]
Bringing back keybindings... check the latest patch

**Comment by pdxwolfy** [comment]
Thanks!

**Comment by pdxwolfy** [comment]
Looks like it works.
