### ISSUE TITLE
LocalHost support gone?

### ISSUE THREAD

**Issue by Dynexxto** [skandasoft/open-in-browsers#44]
Hi, since a recent update (the second to last most recent one I believe. I have lost the functionality to open directly into localhost on my browser. I have localhost ticked in the settings and have my path set to what it was beforehand but it never works. 

Any fixes for this? It's useless to me right now.

**Comment by skandasoft** [comment]
How to View from local host?
Maintain "proj.json" file in the root directory of the project root folder. The file name can be configured from settings, but has to be in the root folder.
Here is sample structure of the file

{
	"localhost": {
		"url": "http://localhost:8000",
		"folder": "C:/Users/admin/myproj/public"
	}
}
There are 2 parameters:

url: This is base url against which the file path will be shown. Just maintaining url would make the file path being added to end of the maintained url.
folder: folder directory will be compared with the path of the file being displayed and will be replaced for eg. in the above case if you view a file under the root directory
/public/view/hello.html  
would be shown as
http://localhost:8000/view/hello.html
This can be maintained differently for each project under each project's root directory.
