### ISSUE TITLE
Safari as Icon

### ISSUE THREAD

**Issue by alexkaessner** [skandasoft/open-in-browsers#5]
Would be nice to have an Icon for Safari on Mac.

_Currently it just looks like this:_
![bottom bar](https://cloud.githubusercontent.com/assets/6615076/12095687/d329c114-b310-11e5-8116-b7022fb5f684.png)
_With these settings activated:_
![settings](https://cloud.githubusercontent.com/assets/6615076/12095689/d34f41be-b310-11e5-8b9a-078cc871d6ad.png)

**Comment by skandasoft** [comment]
check the latest patch.

**Comment by alexkaessner** [comment]
@skandasoft Nice, thanks for the update! :wink:
