### ISSUE TITLE
unused browsers should hide in context menu

### ISSUE THREAD

**Issue by alexkaessner** [skandasoft/open-in-browsers#6]
As I worked around the [missing Icon for Safari](https://github.com/skandasoft/open-in-browsers/issues/5), I've noticed that the settings selection for the browsers won't affect the context menu via right-click.

_Right-click context menu:_
![context menu](https://cloud.githubusercontent.com/assets/6615076/12096294/a0794970-b314-11e5-8416-5d8047c5f903.png)
_…with following settings:_
![settings](https://cloud.githubusercontent.com/assets/6615076/12095689/d34f41be-b310-11e5-8b9a-078cc871d6ad.png)

**Comment by bryanjclark** [comment]
+1

**Comment by skandasoft** [comment]
check the latest patch.

**Comment by alexkaessner** [comment]
@skandasoft Nice, thanks for the update! :wink:
