### ISSUE TITLE
Why i am open my file failed with chrome on centos7?

### ISSUE THREAD

**Issue by jiangyoucai** [skandasoft/open-in-browsers#7]
this plugin is useful
why i am open my file failed with chrome on centos7?
the chrome browser can't run,but the firefox is ok
and i test it on windows,all the browser is ok

**Comment by ragmha** [comment]
I have the same issue with Linux mint, other browsers seems to work but it doesn't open in chrome.I wonder why :D

**Comment by skandasoft** [comment]
how do you open chrome from command line in your os

**Comment by jiangyoucai** [comment]
@skandasoft i can  open chrome from command line with 'google-chrome',and i do ' sudo ln -s /usr/bin/google-chrome /usr/bin/chrome' then it worked

**Comment by skandasoft** [comment]
Can you check the latest patch.  Changed the config.coffee for linux -> chrome to google-chrome.

**Comment by jiangyoucai** [comment]
ok,thank you very much

**Comment by skandasoft** [comment]
Please reopen if it is still a problem
