### ISSUE TITLE
not working for .xhtml files

### ISSUE THREAD

**Issue by garretwilson** [skandasoft/open-in-browsers#8]
This plugin ignores `.xhtml` files.

I even go into the settings and add:

```
.html, .htm, .xhtml
```

Still nothing. It must be ignoring the settings.
1. Please make `.xhtml` a recognized extension by default.
2. Please allow us to add new extensions to the settings---and have them work.

**Comment by skandasoft** [comment]
there is a setting to add the list of file endings with the latest patch.

**Comment by skandasoft** [comment]
assuming latest patch fixed the issue
